// Builds the WASM renderer: compiles wasm/renderer.ts (AssemblyScript,
// entry point -- it locally imports the other wasm/*.ts files) and emits
// public/js/render-wasm.js with the wasm embedded as base64. The generated
// file is NOT committed (gitignored): install.sh and the release workflow
// build it from source so what runs is verifiably what's in the tree, and a
// source checkout without the artifact still works -- the render facade
// falls back to the plain 2D renderer when render-wasm.js is absent.
//
// Runs under BOTH runtimes (whichever the machine has):
//   node  tools/build-wasm.mjs        (uses npx to fetch the pinned compiler)
//   deno run -A tools/build-wasm.mjs  (uses deno's npm: specifier support)
//
// The build stamp is the sha256 of ALL wasm/*.ts sources concatenated in
// sorted-filename order (not a date), so re-running on unchanged source is
// byte-identical and an edit to any non-entry file (e.g. layout.ts) still
// invalidates the skip-rebuild check below -- not just edits to the entry
// file itself.
import { readFile, writeFile, mkdtemp, rm, readdir } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { Buffer } from "node:buffer";

const ASC_VERSION = "0.28.19";
const ASC_FLAGS = ["-O3", "--runtime", "stub", "--noAssert"];
const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const wasmDir = join(repoRoot, "wasm");
const srcPath = join(wasmDir, "renderer.ts");
const outJs = join(repoRoot, "public", "js", "render-wasm.js");

const isDeno = typeof globalThis.Deno !== "undefined";

// Check if rebuild is needed: compare a combined sha256 of every wasm/*.ts
// file (sorted by filename, for a deterministic order) to the one in the
// existing artifact. The generated file has a comment with that sha256; if
// it matches current source, skip compilation (byte-identical rebuild is
// pointless).
const tsFiles = (await readdir(wasmDir)).filter((f) => f.endsWith(".ts")).sort();
const hash = createHash("sha256");
for (const f of tsFiles) {
  hash.update(await readFile(join(wasmDir, f)));
}
const currentSha = hash.digest("hex");
if (await fileExists(outJs)) {
  const existing = await readFile(outJs, "utf8");
  const match = existing.match(/sha256 ([a-f0-9]{64})/);
  if (match && match[1] === currentSha) {
    console.log(`${outJs}: source unchanged, skipping rebuild`);
    process.exit(0);
  }
}

async function fileExists(path) {
  try {
    await readFile(path);
    return true;
  } catch {
    return false;
  }
}

const tmp = await mkdtemp(join(tmpdir(), "snake-wasm-"));
const tmpWasm = join(tmp, "renderer.wasm");

try {
  if (isDeno) {
    execFileSync("deno", ["run", "-A", `npm:assemblyscript@${ASC_VERSION}/asc`, srcPath, "-o", tmpWasm, ...ASC_FLAGS], { stdio: "inherit" });
  } else {
    execFileSync("npx", ["-y", "-p", `assemblyscript@${ASC_VERSION}`, "asc", srcPath, "-o", tmpWasm, ...ASC_FLAGS], { stdio: "inherit" });
  }

  const wasmBytes = await readFile(tmpWasm);
  const sha = currentSha;
  const b64 = Buffer.from(wasmBytes).toString("base64");

  const out = `// GENERATED by tools/build-wasm.mjs -- DO NOT EDIT, DO NOT COMMIT.
// Source: wasm/*.ts (sha256 ${sha})
// Compiler: assemblyscript@${ASC_VERSION}, ${ASC_FLAGS.join(" ")}
// Regenerate: node tools/build-wasm.mjs   (or: deno run -A tools/build-wasm.mjs)
//
// The wasm renderer core, embedded as base64 so it ships inside a plain JS
// file: no separate .wasm fetch, no MIME/static-serving changes, and the
// no-streaming-compile / ~33% size trade-offs are negligible at this size
// (${wasmBytes.length} bytes wasm / ${b64.length} bytes base64). Built from source at
// install/release time -- see install.sh and .github/workflows/release.yml.
(window.__BUILDS__ = window.__BUILDS__ || {}).renderWasm = "render-wasm ${sha.slice(0, 8)}";
window.RENDER_WASM_B64 = "${b64}";
window.instantiateRenderWasm = function () {
  var b = atob(window.RENDER_WASM_B64);
  var bytes = new Uint8Array(b.length);
  for (var i = 0; i < b.length; i++) bytes[i] = b.charCodeAt(i);
  // Synchronous on purpose: at this size sync compile is fine, and it lets
  // the render facade decide wasm-vs-2D before the first frame with no
  // async plumbing in classic scripts.
  var module = new WebAssembly.Module(bytes);
  var instance = new WebAssembly.Instance(module, {
    env: { abort: function () { throw new Error("wasm abort"); } }
  });
  return instance.exports;
};
`;
  await writeFile(outJs, out);
  console.log(`built ${outJs}: wasm ${wasmBytes.length} bytes, base64 ${b64.length} bytes, sha ${sha.slice(0, 8)}`);
} finally {
  await rm(tmp, { recursive: true, force: true });
}
