// Builds the WASM renderer: compiles wasm/renderer.ts (AssemblyScript) and
// emits public/js/render-wasm.js with the wasm embedded as base64 -- the
// embed keeps the repo's ships-source-only release story (no workflow
// changes, no .wasm MIME/static-serving concerns, no separate fetch). The
// generated file IS committed; regenerate with:
//
//   deno run --allow-read --allow-write --allow-env --allow-net --allow-run \
//     tools/build-wasm.ts
//
// (--allow-net is only needed the first time, to fetch the pinned
// assemblyscript npm package into Deno's cache.)
//
// The build stamp is the sha256 of the SOURCE (not a date), so re-running
// on unchanged source is byte-identical and diff-clean.
const ASC_SPECIFIER = "npm:assemblyscript@0.28.19/asc";
const repoRoot = new URL("..", import.meta.url).pathname;
const srcPath = repoRoot + "wasm/renderer.ts";
const outJs = repoRoot + "public/js/render-wasm.js";
const tmpWasm = await Deno.makeTempFile({ prefix: "renderer-", suffix: ".wasm" });

const compile = new Deno.Command("deno", {
  args: [
    "run", "-A", ASC_SPECIFIER,
    srcPath, "-o", tmpWasm,
    "-O3", "--runtime", "stub", "--exportRuntime", "false",
    "--noAssert"
  ],
  stdout: "inherit", stderr: "inherit"
}).spawn();
const status = await compile.status;
if (!status.success) {
  console.error("asc failed");
  Deno.exit(1);
}

const wasmBytes = await Deno.readFile(tmpWasm);
await Deno.remove(tmpWasm);
const src = await Deno.readTextFile(srcPath);
const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(src));
const sha = Array.from(new Uint8Array(digest)).map(b => b.toString(16).padStart(2, "0")).join("");

// base64 in chunks (String.fromCharCode has arg-count limits)
let bin = "";
for (let i = 0; i < wasmBytes.length; i += 0x8000) {
  bin += String.fromCharCode.apply(null, wasmBytes.subarray(i, i + 0x8000) as unknown as number[]);
}
const b64 = btoa(bin);

const out = `// GENERATED by tools/build-wasm.ts -- DO NOT EDIT.
// Source: wasm/renderer.ts (sha256 ${sha})
// Compiler: assemblyscript@0.28.19, -O3 --runtime stub
// Regenerate: deno run --allow-read --allow-write --allow-env --allow-net --allow-run tools/build-wasm.ts
//
// The wasm renderer core, embedded as base64. Committed on purpose: the repo
// ships source-only (release workflow is a git archive), so the deployable
// artifact must live in the tree. Trade-offs of embedding vs a separate
// .wasm fetch (~33% transfer overhead, no streaming compile) are negligible
// at this size (${wasmBytes.length} bytes wasm / ${b64.length} bytes base64) and were
// accepted for Phase 7 -- revisit if the module ever grows past ~200 KB.
(window.__BUILDS__ = window.__BUILDS__ || {}).renderWasm = "render-wasm ${sha.slice(0, 8)}";
window.RENDER_WASM_B64 = "${b64}";
window.instantiateRenderWasm = function () {
  const b = atob(window.RENDER_WASM_B64);
  const bytes = new Uint8Array(b.length);
  for (let i = 0; i < b.length; i++) bytes[i] = b.charCodeAt(i);
  // Synchronous on purpose: at this size sync compile is fine, and it lets
  // the render facade decide 2D-vs-wasm before the first frame with no
  // async plumbing in classic scripts.
  const module = new WebAssembly.Module(bytes);
  const instance = new WebAssembly.Instance(module, {
    env: {
      abort: function () { throw new Error("wasm abort"); },
      "Math.sin": Math.sin, "Math.cos": Math.cos, "Math.round": Math.round
    }
  });
  return instance.exports;
};
`;
await Deno.writeTextFile(outJs, out);
console.log(`built ${outJs}: wasm ${wasmBytes.length} bytes, base64 ${b64.length} bytes, sha ${sha.slice(0, 8)}`);
